cert-manager:
  crds:
    enabled: true
    keep: true

  replicaCount: 1

  resources:
    requests:
      cpu: 30m
      memory: 32M
    limits:
      memory: 64M

  prometheus:
    enabled: true
    servicemonitor:
      enabled: false

  webhook:
    replicaCount: 1
    resources:
      requests:
        cpu: 30m
        memory: 32M
      limits:
        memory: 64M
    timeoutSeconds: 20

  cainjector:
    enabled: true
    replicaCount: 1
    resources:
      requests:
        cpu: 30m
        memory: 32M
      limits:
        memory: 64M

  startupapicheck:
    enabled: true
    resources:
      requests:
        cpu: 30m
        memory: 32M
      limits:
        memory: 64M

cert-manager-csi-driver:
  resources:
    requests:
      cpu: 30m
      memory: 32M
    limits:
      memory: 64M
  app:
    logLevel: 1 # 1 = info, 2 = debug
  rbac:
    create: true
