tailscale-operator:
  ingressClass:
    enabled: true

  installCRDs: true

  # Use pre-existing sealed secret for oauth
  # Setting clientSecret triggers volume mount, oauthSecretVolume overrides source
  oauth:
    clientSecret: "placeholder"
  oauthSecretVolume:
    secret:
      secretName: operator-oauth

  operatorConfig:
    defaultTags:
      - tag:k8s-operator-nbg1-prod1
    resources:
      requests:
        cpu: 25m
        memory: 100Mi
      limits:
        memory: 100Mi

  proxyConfig:
    defaultTags: "tag:k8s-nbg1-prod1"
    # Use ProxyClass with metrics enabled
    defaultProxyClass: "default"
