---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: grafana
spec:
  encryptedData:
    password: AgBf84R7U8BL5ldFpryrJpOXy+VVJKAXSNq7Gs2YXgVQqrMwi6GOpsTrgqN4MLhmp2fdMR2oRvpRrQbMRt9IkLdxKKFvvO0Godjgk97OH9jTIfXvCkC5z8wTQRkUzUYkwZ2OZmhwwJerPDKpugiaXFMhMyBnHtc7tRIYqZgSZWkxbJuG3E8qwl8w7ifIGhZE+EyyOTdQsOCJ5Ased/PdfxEfewpy8NB2hzLDmIVKJXoy4oh9owqvv/DBB5ZNsad+X/MBITrhoX5niWtf857UhML2lu8WkfqPWcXMtzcWzzG2bV6cd56H6e3elP2itA7isGXCPdnwBCvNL2AyzdMELsd1RGfEOWNQd+QdvUOA839DrzfzRlo0XtyjUyTnSqk0bACqjn6coq9g00V7mO3e68w4PwLCwYRMuWqsV0NdGYr9lISfu3fkHgeKxmYvw2VopNvrOdFhYtrmexI2Hh3Dbf56YJVSnXt+GRpOUkZ1qLyhhHhl7jRT72sQQcyeoHn33FP/plkTvg51I2ZS2siYoMZZL6M24/Xq8b8oktTquipo2bnW8SFPVJ+9IMmAKcBWMNbRXNrgzSb91szX1wYQFkPKNv2t+kU9eVD+McICosKlQX4bMuW669As6OcG1Ly/A5rvE8xl2mm/c1wRerKVbQRTTz2Eykhcw7VnLkbRf9XdlhWLzkg8PPvnK6LkPM+lN+4iuFKLj+MJ1vnqNBv7g6zs
    username: AgATMqCUgKKffU8olTxmgIw18obpUDDm/dtiP4xQroGP5q3e9W/qyJpOXXXdaHPaJPgDr1uHH9kHHfwv89U1tkvxR7ntnqyWxUmE2NvT8i1XC8L5fTWegBcQhUGW9+SGsBwHsH/1X8ef43masOCWojKgHsuOaBwekYS4v8DtKiUXuS0S7O7uP9aEPH37KNqIljVOtcxgKPlKidV4g2tWlvyKUK3ocqYDWi/5NWumowCbuEz92yhUBd9qqGMhHaue8P/u82gBh3HQwVSoqAl6A2tPm+TlquD1hHLQFnkIV6EIk0qdgqEoMi1HYEZqR3Qwd9RYGQ8F/nItrtte+OzqIijNNQ3frc3hYac6GuKc7IYGRxBhVgcrVOg2RrO7psnI0t1uXfpOdgavhv3Ae94av0HVVq8B0XTUbARTo9ra0deSeysqEhcQYDpNXz4XxUo5oa84WwEZ68VUeUksAdfD4D9rcSAFiFSNFXe22HjOdEFdThrmAlVCiZCSNAm0ZiopKDbJWHevJpRJIasE53U+QySFd1PbGB/aLRgmadbfSD0zcns/c5d+K7rvxKaEp2FwVJU8k8YtUFqEOI6QytNUINN+l0G4jEGr60A8WLFQ2ImpA58DSzzFi11lAau2YviwUVBgwlat3ByK7S+J8eJp4S0u7LgP/2cFX21ekAAyzyuWmHwbSIQfSgGHK9EecVJTsiarg6ci9w==
  template:
    metadata:
      name: grafana-admin
      namespace: grafana
